### ISSUE TITLE
Usage for async methods?

### ISSUE THREAD

**Issue by adrianwiechec-at-optilyz** [Xample/ts-throwable#1]
How do I use ts-throwable for an async method?

If I try this:
```
async function asyncBrokenMethod(): Promise<number & throwable<CustomError>> {
 if (Math.random() < 0.5) { return Promise.resolve(42)} else {
  throw new CustomError("Boom!");}
}
try {
    const answer: number = await asyncBrokenMethod()
}
catch(error){
    const typedError = getTypedError(error, asyncBrokenMethod);
}
```
, then `typedError` is typed as `never` :(

TS playground [here](https://www.typescriptlang.org/play?#code/MYewdgzgLgBApgJwSBAVAngBzjAvDAZXQFsAjEAGwAoAiAQRk2WwSnRnAvagAtEcoIGNBQCscCDQCUAbgCwAKDbYYvZAHcAhqQpwAPKngAPKHDAATCDACiSFAD48MAN6KY7mAG1EyNOIC6APwAXDCo8goAvorKOADmcFCoPBrauhjYBo74hnAmZpaqKSBaOvoAlmAAZohhjoFhMKFgcABuiBGxMKSaEOXAAGIArmDAUOXgTlQAdLOaYOih8+ie-lJ4jsud4sbAcJjj4BAA8lUGxqYWVj19gyNjE2DZMAlJxaXp4noASolDCGAMvpUPZ7BFQJBYK8geZbL4nOc8pdCjd+sNRocnlQfChQiMANZgEpgAA0RVSZQAsokeCBzKFUOtcI5sXYEDBert9piTmcQbJFIpgBRelYAMJDETEOEoC4FKwy9muBQeGAQ6AIIZjFBUTBDHT9GDmRKacoUCChDWVOLrZWq1UQIYsKgClUeaJRRS9dCjGBVe6YjkQH3AABCyHxZmpvDpLtCAAVkMRyhB9GAhmRagAycklNL6CVSxWglxucpVGBUSmaXjTBDzcwgYgumB6GAABmmAFZbTAEH8ATBE02U3A6xJKO0qAAWABMUki8HNODtufUMBa68LgmlbNooZATYAhNIZB6PYKFOrYN7RgB1euYJy34CVpmOZVQBDsVfua8cyB1EQZoM1IWp8E0LRyhvYNRnDEBIzAaNaXMF1FA9YAa2AHhWV8KRfzVI5YFiWE2ScaFxFI3xcJQMkX3gxDkLpV1z0vF8H00TAXSAA)

**Comment by Xample** [comment]
Hello, it seems that I actually forgot to unwrap errors from a promise…

for instance if you replace

`type getThrowableType<T> = T extends throwable<infer T> ? T : never;`

with 

`type getThrowableType<T> = T extends PromiseLike<throwable<infer T>> ? T : never;`

it will work in this special case, I however need to think about a clean way to achieve this even for recursive promises (promise of promises)

we should be able to unwrap promises using `Awaited` [which is built in ts 4.5](https://stackoverflow.com/questions/48011353/how-to-unwrap-the-type-of-a-promise)

**Comment by Xample** [comment]
Okay, here is how to unwrap the promises:

`type exceptionsOf<T extends basicFunction> = getThrowableType<Awaited<ReturnType<T>>>;`

And if anyone needs a support for TS <4.5, there is a [self implementation of Awaited](https://stackoverflow.com/questions/48011353/how-to-unwrap-the-type-of-a-promise)

**Comment by Xample** [comment]
@adrianwiechec-at-optilyz fixed on master, TS playground [here](https://www.typescriptlang.org/play?#code/MYewdgzgLgBApgJwSBAVAngBzjAvDAZXQFsAjEAGwAoAiAQRk2WwSnRnAvagAtEcoIGNBQCscCDQCUAbgCwAKDbYYvZAHcAhqQpwAPKngAPKHDAATCDACiSFAD48MAN6KY7mAG1EyNOIC6APwAXDCo8goAvorKOADmcFCoPBrauhjYBo74hnAmZpaqKSBaOvoAlmAAZohhjoFhMKFgcABuiBGxMKSaEOXAAGIArmDAUOXgTlQAdLOaYOih8+ie-lJ4jsud4sbAcJjj4BAA8lUGxqYWVj19gyNjE2DZMAlJxaXp4np0WuWm5noAEqJIYIMAZfSoezQmQRUCQWCvCHmWy+JznPKXQo3frDUaHJ5UHwoUIjADWYBKYAANEVUmUALKJHggcyhVDrXCOIl2BAwXq7fYEk5nKGyRSKYAUXpWADCQxExFRKAuBSsyr5rgUHhg8OgCCGYxQVEwQx0-Rg5kSmnKFAgoX1lTi6y1Op1ECGLCo4u1HmiUUUvXQoxgVXuBP5EGDwAAQsgyWYmbxWd7QgAFZDEcoQfRgIZkWoAMjpJTS+nlio10JcbnKVRgVAZml40wQ83MIGI3pgehgAAZpgBWF0wBAgsEwDOd7NwVsSSjtKgAFgATFJIvA7ThXSX1DAWnuK4IlbzaDGQJ2AITSGT+-0ShR62BB0YAdTbmCcL+ADc5ji1UAIOwO7uE+-KQOoiDNPmpC1Pgmi-M+UajHGIAJmASYsuY3qKP6wDNsAPA8r4UggTAAD05EwAAciURTZjADGxOYkYwEenYapebgeGBzEak4SLiCip7EggtLfqh6GYayPp3g+37vpomDekAA)

**Comment by adrianwiechec-at-optilyz** [comment]
Works splendidly now, thanks very much! :bow:
